apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  secretStoreRef:
    name: SECRET_STORE_NAME
    kind: SECRET_STORE_TYPE
  target:
    name: test-secret
  data:
    - remoteRef:
        key: SECRET_PATH
        property: test-key
      secretKey: test-key
