apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - image: docker.io/google/pause:latest
      name: test-container
      volumeMounts:
        - name: test-volume
          mountPath: /mnt
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-volume
