apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  labels:
    component: nginx
spec:
  containers:
    - image: ghcr.io/ocp-on-nerc/openshift-tests:latest
      name: test-container
      env:
        - name: WHOAMI_PORT_NUMBER
          value: "8080"
      ports:
        - name: http
          containerPort: 8080
