apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  labels:
    component: nginx
spec:
  containers:
    - image: docker.io/nginxinc/nginx-unprivileged
      name: test-container
      ports:
        - name: http
          containerPort: 8080
