apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
    - image: docker.io/alpine:latest
      name: test-container
      command:
        - sh
        - -c
        - |
          apk add --update tini
          exec tini sleep inf
      startupProbe:
        exec:
          command:
            - wget
            - -O
            - /dev/null
            - http://test-pod1:8080
        initialDelaySeconds: 5
        periodSeconds: 1
