apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
    - image: ghcr.io/ocp-on-nerc/openshift-tests:latest
      name: test-container
      startupProbe:
        exec:
          command:
            - wget
            - -O
            - /dev/null
            - http://test-pod1:8080
        initialDelaySeconds: 5
        periodSeconds: 1
